# version: "3.11" 이 부분은 docker compose 2.25 이상 부터는 필요없다고 한다.
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"