# Generated by Django 5.0.6 on 2024-06-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_testcol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testcol',
        ),
    ]
