# Generated by Django 5.0.6 on 2024-05-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonModel',
        ),
    ]
