# Github Actions CI/CD
---
name: Checks # Workflow 이름

on: [push] # 어떤 액션을 받으면 활성화해줄지? push로 작성하면 푸쉬할 때 트리거된다

jobs: # 어떤 일을 할건지
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-20.04 # 어디서 돌릴것인가 ? 어떤 환경 ?
    env:
      working-directory: ./Django/django-project-youtube

    steps: # 작업 단계
      # - name: Login in to Docker Hub
      #   uses: docker/login-action@v1 # 깃허브에서 제공하는 로그인 모듈
      #   with: # 저번에 레포지토리에 저장한 토큰과 아이디를 같이 보내줌
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out - pull repostirty code # Github에 있는 코드를 작업 환경으로 가져오는 역할
        uses: actions/checkout@v2 # 이것도 깃허브에서 제공하는 모듈 우리가 작성한 코드를 불러올 수 이씀

      - name: Run Test-Code
      # 이때는 uses가 아닌, 모듈을 사용하는게 아니라 도커에 들어온 상태이고 코드에서 테스트를 하기위해 run.
        run: docker-compose run --rm app sh -c 'python manage.py' wait_for_db && \
        docker-compose run --rm app sh -c 'python manage.py test'
        working-directory: ${{ env.working-directory }}
      
      - name: Run Flake8 for Linting # pep8 style guide를 잘 준수하고 있는지 체크
        run: docker-compose run --rm app sh -c 'flake8'
        working-directory: ${{ env.working-directory }}